#!/bin/sh /etc/rc.common
START=96
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c 'sleep 15; /usr/share/simpleui/update-rules.sh >/tmp/simpleui/boot.log 2>&1'
    procd_set_param respawn 0 0 0
    procd_close_instance
}

stop_service() {
    /usr/share/simpleui/disable-routing.sh >/dev/null 2>&1 || true
}

reload_service() {
    /usr/share/simpleui/update-rules.sh >/dev/null 2>&1 || true
}

service_triggers() {
    procd_add_reload_trigger simpleui
}
