#!/bin/sh /etc/rc.common
START=96
STOP=10

start() {
    mkdir -p /tmp/simpleui
    rm -rf /tmp/simpleui-update.lock
    (
        sleep 15
        /usr/share/simpleui/update-rules.sh >/tmp/simpleui/boot.log 2>&1
    ) &
}

stop() {
    /usr/share/simpleui/disable-routing.sh >/dev/null 2>&1 || true
}

reload() {
    (
        /usr/share/simpleui/update-rules.sh >/tmp/simpleui/reload.log 2>&1
    ) &
}
